#!/bin/sh

# organize code

git diff HEAD^ HEAD --name-only -- '***.ts' | while read filename; do
  echo "Organizing: $filename"
  tsco --organize --file "$filename"
done

# format code

eslint

# compile code

tsc
